### ISSUE TITLE
Job lock not working properly

### ISSUE THREAD

**Issue by riotxstudios** [jellyton255/ef_shops#12]
EDIT: this has been fixed simply do the following in shop_items
	taxi = {
			water = { price = 1, defaultStock = 50, category = 'Snacks',jobs = {lspd = 1}},
			burger = { price = 3, defaultStock = 50, category = 'Snacks', jobs = {lspd = 1}},
			
			
			(edit them to ur needs but make sure the grade is above 0)

Framework: QBOX

Job lock function does not work correctly

Multiple attempts to make it work have been made with no success

shop_items.lua

	normal = {
		water = { price = 1, defaultStock = 50, category = 'Snacks',jobs = 'taxi' },
		burger = { price = 3, defaultStock = 50, category = 'Snacks', jobs = 'taxi'},
	},

When job is mechanic you cannot buy any items which is what its supposed to be but then when switching to Taxi job it is still locked

then vice versa whenever you are taxi job u can buy things but then change to mechanic and youll still be able to buy things even tho ur not meant to

We attempted to make the job lock on the locations instead or aswell as shop_items.lua

locations.lua

normal = {
        label = "City Resource",
        model = {
            `g_m_m_mexboss_01`
        },
        coords = {
            vector4(-2293.29, 356.25, 174.66, 295),
        },
        shopItems = "normal",
        blip = {
            sprite = 606,
            color = 7,
        },
        job = "taxi"
    },

same result as before

**Comment by AJCorwin** [comment]
Issue persist even after latest release (1.20)

**Comment by riotxstudios** [comment]
Issue persist even after latest release (1.20)

**Comment by riotxstudios** [comment]
EDIT: this has been fixed simply do the following in shop_items
	taxi = {
			water = { price = 1, defaultStock = 50, category = 'Snacks',jobs = {lspd = 1}},
			burger = { price = 3, defaultStock = 50, category = 'Snacks', jobs = {lspd = 1}},
			
			
			(edit them to ur needs but make sure the grade is above 0)

**Comment by riotxstudios** [comment]
EDIT: this has been fixed simply do the following in shop_items
	taxi = {
			water = { price = 1, defaultStock = 50, category = 'Snacks',jobs = {lspd = 1}},
			burger = { price = 3, defaultStock = 50, category = 'Snacks', jobs = {lspd = 1}},
			
			
			(edit them to ur needs but make sure the grade is above 0)
