### ISSUE TITLE
Warning: could not find file `web/build/index.html` (defined in fxmanifest.lua:33)

### ISSUE THREAD

**Issue by Yukon187** [jellyton255/ef_shops#14]
Fxmanifest is missing folder location 'Build' and I am on latest build and all QBX dependencies and Ox_target. I can look at the ped in stores and click the button to Browse shop. But once I do I cannot  move my ped but mouse is free to move and no menu shows up . I have enabled debug and no errors are printing on sever or client side.

**Comment by jellyton255** [comment]
You cannot download from the code, you need to download the release. https://github.com/jellyton255/ef_shops/releases/tag/v1.2.0
