### ISSUE TITLE
Feat: Job and Job Grade Requirements

### ISSUE THREAD

**Issue by jnccloud** [jellyton255/ef_shops#2]
This would be an amazing resource to organize all of the PD armory items. The only area I find it lacking is the ability to add jobs/grades. 

If I am able to figure out how to properly implement I hope to PR but otherwise would like to make this request known. Thank you.

**Comment by jellyton255** [comment]
Yeah thanks for the issue, I am going to do this, but I would have completely forgotten without a reminder. Thank you thank you.

**Comment by jnccloud** [comment]
No problem!

Do you think it would be trivial to replace the vending machines in ox shops.lua with this as well?

**Comment by jnccloud** [comment]
I was looking at some streams from your server. Do you have any tips or resources you can share for server side sirens? I'd be so thankful

**Comment by jellyton255** [comment]
Implemented as of https://github.com/jellyton69/ef_shops/commit/af719d522744baf59528630dcbbb0829b281324b
